AllCops:
  TargetRubyVersion: 2.5.3
  Exclude:
    - db/schema.rb
    - bin/*
    - config/**/*
    - Gemfile

Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 15