version: '3'
services:
  db:
    container_name: "kryla_api_db"
    image: postgres:9.5-alpine
    volumes:
      - data-postgres:/var/lib/postgresql/data
  backend:
    container_name: "kryla_api_s_rails"
    build: .
    command: /bin/sh -c "rm -f /myapp/tmp/pids/server.pid && bundle exec rails s -p 3000 -b 0.0.0.0"
    volumes:
      - .:/myapp:rw
      - bundle:/bundle
    ports:
      - 3000:3000
    depends_on:
      - db
    env_file:
      - .env
volumes:
  data-postgres:
    driver: local
  bundle:
    driver: local