version: '3'
services:
  redis:
    image: redis
  rails:
    build: .
    image: ma-rails
    command: /bin/sh -c "rm -f /myapp/tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0"
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - redis
    env_file:
      - .env
  sidekiq:
    image: ma-rails
    command: sidekiq -C config/sidekiq.yml
    depends_on:
      - redis
    env_file:
      - .env
volumes:
  pg-data:
    driver: local