version: '3'
services:
  db:
    image: postgres:9.6
    container_name: "db"
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - pg-data:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
  rails:
    build: .
    image: ma-rails
    command: sh -c 'cd /myapp && bundle install && rails s -b 0.0.0.0'
    depends_on:
      - db
      - redis
    ports:
      - 3000:3000
    env_file:
      - .env
  sidekiq:
    image: ma-rails
    command: sidekiq -C config/sidekiq.yml
    depends_on:
      - redis
      - db
    env_file:
      - .env
volumes:
  pg-data:
    driver: local
  redis-data:
    driver: local