version: '3'
services:
  db:
    image: postgres:9.6
    env_file:
      - .env
    volumes:
      - pg-data:/var/lib/postgresql/data
  redis:
    image: redis
  rails:
    build: .
    image: ma-rails
    command: /bin/sh -c "rm -f /myapp/tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0"
    volumes:
      - .:/myapp
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
    env_file:
      - .env
  sidekiq:
    image: ma-rails
    command: sidekiq -C config/sidekiq.yml
    volumes:
      - .:/myapp
    depends_on:
      - redis
      - db
    env_file:
      - .env
volumes:
  pg-data:
    driver: local