default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  redis:
    url: <%= ENV["REDIS_URL"] %>
    namespace: <%= ENV["REDIS_NAMESPACE"] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default